name: Compile changelogs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  CompileCL:
    runs-on: ubuntu-latest
    if: github.repository == 'NebulaSS13/Nebula'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with: 
          fetch-depth: 0 # Otherwise, we will fail to push refs
      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml bs4
      - name: Compile CL
        run: |
          git checkout -f dev
          git reset --hard origin/dev
          python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit And Push
        run: |
          git config --local user.email "NebulaSS13Bot@gmail.com"
          git config --local user.name "NebulaSS13Bot"
          git commit -m "Automatic changelog compile [ci skip]" -a
          git push https://${{ secrets.BOT_TOKEN }}:x-oauth-basic@github.com/NebulaSS13/Nebula.git dev
